### ISSUE TITLE
Problem with window dimensions

### ISSUE THREAD

**Issue by NathanBnm** [dcharles525/crypt#12]
I have this issue since the last update. The windows doesn't fit to the screen and I can't make it full-screen or vertically resize it.

Here is a screenshot:
![image](https://user-images.githubusercontent.com/45366162/54185701-fa3d6480-44a9-11e9-982f-7d25cefaf6a4.png)

**Comment by dcharles525** [comment]
Hmm this is an odd one. Ca you tell me your screen dimensions? I emulated 4:3, 3:2 and 16:10 ratio but couldn't seem to get it to not resize.

**Comment by dcharles525** [comment]
Didn't mean to close it :smile:

**Comment by NathanBnm** [comment]
I have a 15,6'' screen with a maximum resolution of 1366 x 768.

**Comment by dcharles525** [comment]
I think I was able to fix this, I am going to try and get an update out asap.

**Comment by NathanBnm** [comment]
Okay great! I will tell you if it's not :smile:
