### ISSUE TITLE
Problem with translations

### ISSUE THREAD

**Issue by NathanBnm** [dcharles525/crypt#13]
I have this issue since the last update too. Some translations aren't working like here in this screenshot:
![image](https://user-images.githubusercontent.com/45366162/54185807-31137a80-44aa-11e9-822c-ca828faafb3b.png)

**Comment by NathanBnm** [comment]
Translations seems to appeared then. Closing.

**Comment by NathanBnm** [comment]
@dcharles525 actually theses strings are only translated with BTC (See the following screenshot) but not with other currencies.

![image](https://user-images.githubusercontent.com/45366162/54352967-1d574800-4653-11e9-9c8d-69d31b9fe09c.png)

**Comment by dcharles525** [comment]
May have fixed this, pushing out a release now.

**Comment by NathanBnm** [comment]
Okay great!
