### ISSUE TITLE
Problem with date format

### ISSUE THREAD

**Issue by NathanBnm** [dcharles525/crypt#14]
Since the last update date format isn't displaying correctly. Here is a screenshot:
![image](https://user-images.githubusercontent.com/45366162/54185896-6029ec00-44aa-11e9-8209-eec23131958f.png)

**Comment by dcharles525** [comment]
Just fixed this issue, I switched to display values to reduce client side calculations and forgot to switch over the data type for the dates. 

Thank you for pointing this out :+1:
