### ISSUE TITLE
Why is Bitcoin currency appearing two times ?

### ISSUE THREAD

**Issue by NathanBnm** [dcharles525/crypt#15]
With different values. Translation issue? Here is a screenshot:
![image](https://user-images.githubusercontent.com/45366162/54186081-d29acc00-44aa-11e9-96e1-cf92c97a957d.png)

**Comment by dcharles525** [comment]
This was a translation issue, Bitcoin Cash was translated to just Bitcoin, i set it back to Bitcoin Cash.

**Comment by NathanBnm** [comment]
Okay sorry I didn't noticed that, but solved :smile:

**Comment by dcharles525** [comment]
Its all good thank you!
