### ISSUE TITLE
Remove app name from Summary

### ISSUE THREAD

**Issue by danrabbit** [dcharles525/crypt#2]
https://github.com/dcharles525/crypt/blob/7c57cf1138a6fe9326f2c8c9c3e10c2460745358/data/com.github.dcharles525.crypt.appdata.xml#L8

Since the application name is often already shown alongside the summary, this will cause your listing to appear repetitive. Summaries should also not typically contain punctuation. Currently your AppCenter banner would look like this:

---

### Crypt
Crypt - Making the crypto market more cryptic!

---

It should look like

---

### Crypt
Making the crypto market more cryptic

---

**Comment by dcharles525** [comment]
Fixed in latest release (1.0.2).
