### ISSUE TITLE
Include additional relevant categories

### ISSUE THREAD

**Issue by danrabbit** [dcharles525/crypt#3]
https://github.com/dcharles525/crypt/blob/7c57cf1138a6fe9326f2c8c9c3e10c2460745358/data/com.github.dcharles525.crypt.desktop#L5

You might want to include [additional categories](https://specifications.freedesktop.org/menu-spec/latest/apas02.html) to help users find your app such as:
* Finance
* Office

**Comment by dcharles525** [comment]
Fixed in latest release (1.0.2). Thanks for the suggestions!
