### ISSUE TITLE
Better icon

### ISSUE THREAD

**Issue by ranfdev** [dcharles525/crypt#30]
The "crypt" text on the icon is not readable, it's too dark... So i propose this new icon.
If you like it, i'll send you the svg file (github doesn't let me upload svg images here, i don't know why)

![crypt](https://user-images.githubusercontent.com/23294184/57145392-69a54580-6dc3-11e9-8348-c34a1f63b0e5.png)

**Comment by dcharles525** [comment]
First off, thanks for contributing!

I love the colors! I was thinking go as far as just remove "Crypt" from the icon all together. I would like to test it out on my system, you can send it to me via email if that's ok (dcharles525 at gmail.com)

**Comment by ranfdev** [comment]
Oh nevermind, github let me upload zip files... inside you can find the svg file
[crypt.svg.zip](https://github.com/dcharles525/crypt/files/3142663/crypt.svg.zip)

**Comment by dcharles525** [comment]
Thank you!

**Comment by dcharles525** [comment]
I've updated the icon, thank you for the work, it'll be updated on appcenter hopefully next week.

**Comment by ranfdev** [comment]
:smiley:
