### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by dcharles525** [dcharles525/crypt#44]
- [x] I don't like how small the tabs are
- [x] The colors are inconsitent in the background
- [x] Data list per coin looks awful

**Comment by hanaral** [comment]
The tabs shouldn't be the default gtk tabs as elementary HIG only recommends Granite modebuttons etc. (hence why gtk tabs look broken in the elementary stylesheet)

**Comment by dcharles525** [comment]
@hanaral Thanks! I will be upgrading the tabs in a later update, for now I just added some padding. The other two I will get the bg colors to all match then I have some plans to redesign the detailed coin page.
